### ISSUE TITLE
no module named 'surok.logger'

### ISSUE THREAD

**Issue by w1r0x** [Difrex/surok#8]
tag 0.7.4.1

on run I get:

Traceback (most recent call last):
  File "surok.py", line 9, in <module>
    from surok.discovery import resolve
  File "/opt/surok/surok/discovery.py", line 4, in <module>
    from .logger import info, warning, error, debug
ImportError: No module named 'surok.logger'

**Comment by Difrex** [comment]
closed in V0.7.4.2
